---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/login":
    post:
      summary: User login
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      role:
                        type: string
                      email:
                        type: string
                      token:
                        type: string
                    required:
                    - id
                    - name
                    - role
                    - email
                    - token
                required:
                - user
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
              required:
              - email
              - password
              - role
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
