---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/admin/users":
    post:
      summary: Create a new user (admin only)
      tags:
      - - Admin Users
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '201':
          description: user created
        '422':
          description: invalid request
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - user
              properties:
                user:
                  type: object
                  required:
                  - email
                  - password
                  - password_confirmation
                  - name
                  - role
                  properties:
                    email:
                      type: string
                      example: student3@example.com
                    password:
                      type: string
                      example: '123456'
                    password_confirmation:
                      type: string
                      example: '123456'
                    name:
                      type: string
                      example: Prenume3 Nume3
                    role:
                      type: string
                      enum:
                      - student
                      - teacher
                      example: student
        required: true
  "/api/login":
    post:
      summary: User login
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: successful login
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
