default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: eduapp_backend_development

test:
  <<: *default
  database: eduapp_beckend_test
